#!/bin/bash

# icon=$HOME/.xlock/icon.png
tmpbg=/tmp/screen.png
scrot "$tmpbg"
convert "$tmpbg" -scale 10% -scale %1000 "$tmpbg"
# convert "$tmpbg" -gravity center -composite -matte "$tmpbg"
dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Stop
i3lock -i "$tmpbg"
rm "$tmpbg"