#!/bin/bash
set -Eeuxo pipefail

dev_id=`xinput list | grep -i 'TouchPad' | awk '{ print $6 }' | sed 's/id=//' | tr '\n' ' '`

cur_mode=`xinput list-props $dev_id | grep "Device Enabled" | tr ": " "\n" | tail -1`

enable=''
if [ $cur_mode -eq 1 ] ; then
    enable='--disable'
else
    enable='--enable'
fi

for devnum in $dev_id; do
    xinput "$enable" "$devnum"
done
