#!/hint/bash

# load shell plugins
# shellcheck disable=SC1090
source ~/.config/zsh/plugins.zsh

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
export HYPHEN_INSENSITIVE="true"

# Uncomment the following line to display red dots whilst waiting for completion.
export COMPLETION_WAITING_DOTS="true"

# set window title to working directory + last command name
function preexec() {
  SHELL_PREV_CMD=${1}
  print -Pn -- "\e]2;$(shrink_path -t -1) %# " && print -n -- "${SHELL_PREV_CMD}\a\a" # second \a sends bell signal
}

# set window title after command in case we changed directories (cd)
function promptcmd() {
  RET_CODE="$?"
  print -Pn -- "\e]2;$(shrink_path -t -1) %# " && print -n -- "${SHELL_PREV_CMD} ($RET_CODE)\a\a"
}
precmd_functions+=(promptcmd)

# User configuration
export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=1000000000
export SAVEHIST=1000000000
setopt EXTENDED_HISTORY

PATH=~/.local/bin:$PATH

# env var and PATH setup
source ~/.profile

# shellcheck disable=SC1091
source "$HOME"/.bash_aliases

# invoke cat with no args and enter a key to get its keycode
# bindkey -l will give you a list of existing keymap names
# bindkey -M <keymap> will list all the bindings in a given keymap
# https://zsh.sourceforge.io/Doc/Release/Zsh-Line-Editor.html#Standard-Widgets
bindkey "^[[1;5C" forward-word    # ctrl + right
bindkey "^[[1;5D" backward-word   # ctrl + left
bindkey '^H' backward-delete-word # ctrl + backspace
bindkey '^[[3~' delete-char       # delete
bindkey '^[[3;5~' kill-word       # ctrl + delete
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line

# tab completion
# bindkey '^I' autosuggest-accept
bindkey '\t\t' autosuggest-accept

# outer parens are to silence control messages
( (cat ~/.cache/wal/sequences && dispatch_shell_colors) &)

# nvm setup
# shellcheck disable=SC2155
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
# shellcheck disable=SC1091
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# pyenv setup
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# start in workspace unless this in an integrated vscode terminal
[ -z "$VSC" ] && ws
