#!/hint/bash

# load shell plugins
# shellcheck disable=SC1090
source ~/.config/zsh/plugins.zsh

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
export HYPHEN_INSENSITIVE="true"

# Uncomment the following line to display red dots whilst waiting for completion.
export COMPLETION_WAITING_DOTS="true"

# set window title to working directory + last command name
function preexec() {
  SHELL_PREV_CMD=${1}
  print -Pn -- "\e]2;$(shrink_path -t -1) %# " && print -n -- "${SHELL_PREV_CMD}\a\a" # second \a sends bell signal
}

# set window title after command in case we changed directories (cd)
function promptcmd() {
  RET_CODE="$?"
  print -Pn -- "\e]2;$(shrink_path -t -1) %# " && print -n -- "${SHELL_PREV_CMD} ($RET_CODE)\a\a"
}
precmd_functions+=(promptcmd)

# User configuration
export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=1000000000
export SAVEHIST=1000000000
setopt EXTENDED_HISTORY

PATH=~/.local/bin:$PATH

# env var and PATH setup
source ~/.profile

# shellcheck disable=SC1091
source "$HOME"/.bash_aliases

# invoke cat with no args and enter a key to get its keycode
# bindkey -l will give you a list of existing keymap names
# bindkey -M <keymap> will list all the bindings in a given keymap
# https://zsh.sourceforge.io/Doc/Release/Zsh-Line-Editor.html#Standard-Widgets
bindkey "^[[1;5C" forward-word    # ctrl + right
bindkey "^[[1;5D" backward-word   # ctrl + left
bindkey '^H' backward-delete-word # ctrl + backspace
bindkey '^[[3~' delete-char       # delete
bindkey '^[[3;5~' kill-word       # ctrl + delete
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
bindkey '^K' clear-screen

# tab completion
# bindkey '^I' autosuggest-accept
# bindkey '\t\t' autosuggest-accept

# outer parens are to silence control messages
(cat ~/.cache/wal/sequences &)

# nvm setup
# shellcheck disable=SC1091
source /usr/share/nvm/init-nvm.sh

# start in workspace unless this in an integrated vscode terminal
[ -z "$VSC" ] && ws

export MEMOS_URI=https://memos.homelab.akmin.dev
export MEMOS_TOKEN='eyJhbGciOiJIUzI1NiIsImtpZCI6InYxIiwidHlwIjoiSldUIn0.eyJuYW1lIjoiYWttaW4iLCJpc3MiOiJtZW1vcyIsInN1YiI6IjEiLCJhdWQiOlsidXNlci5hY2Nlc3MtdG9rZW4iXSwiZXhwIjoxNzU5NzA4MjIwLCJpYXQiOjE3NTcxMTYyMjB9.uGO0P455axAkUbnney9vcJUHj5hM743qJmrGQxV72AM'
