#!/bin/bash
set -Eeuxo pipefail

printf "Are you sure you want to remove the dotfiles repo? [Y/n] "
read response
if [[ "$response" =~ [^Yy] ]]; then
    echo "Exiting"
    exit
fi

if ! yadm diff --quiet || yadm status | grep -q 'ahead'; then
    echo "Uncommitted/unpushed changes"
    exit 1
fi

chsh -s "$(cat ~/.yadm/orig_shell)"
yadm checkout old
rm -rf ~/.yadm ~/.oh-my-zsh ~/.fzf* ~/.gdbinit
echo "Logout and log back in to see changes"
