#!/hint/bash
# shellcheck disable=all

exit 7 # just exit if somehow I manage to execute this

#
# my unix cheat sheet
#
# inspiration: https://github.com/awdeorio/dotfiles/blob/57004769418a8c16d816fae951a7d2f023fcec0f/.always_forget.txt
#

# package management
pacman -Runs PACKAGE # remove a package, all it's unnecessary dependencies, any unneeded packages, and any configuration files
pacman -Qm           # list all installed AUR packages
pacman -Ql PACKAGE   # list all files owned by a package
pacman -Qo FILE      # find the package that owns a file
pacman -Qi PACKAGE   # display info about a package, including dependents
pacman -Sc           # remove uninstalled package tarballs from cache
pacman -Scc          # remove all package tarballs from cache

pacman -Qdtq                   # list all orphaned packages
pacman -D --asexplicit PACKAGE # mark a package as explicitly installed

pacman -U PACKAGEFILE # install a package from local source (.pacman)

# patching

diff -Naur ORIGINAL_FILE MODIFIED_FILE >PATCHFILE.patch # generate a patch file
patch -u FILE_TO_PATCH PATCHFILE                        # patch a file using a patch file

# checksum verification

sha512sum -c KEY_FILE.sha512sum # check a file against its sha512 checksum

# users & groups

sudo usermod -a -G GROUPNAME[,GROUPNAME2] USERNAME # add a user to a group

# disks

sudo fdisk -l # list disks and metadata

sudo mkfs.vfat /dev/sdaX # format a drive as FAT32

sudo dd if=ABSOLUTE_ISO_PATH of=/dev/sdaX bs=8M status=progress # write an image to a usb drive

sudo eject /dev/sdaX # eject a drive

# battery

for BAT_PATH in $(upower -e | grep BAT); do upower -i "$BAT_PATH"; done # print info for all batteries

# nmap

sudo nmap -vv --stats-every 10s -n -Pn -sT -sU -p- ADDRESS # scan all ports for TCP and UDP, takes forever

# diffing

fdupes -r DIRECTORY
fdupes -rd DIRECTORY
